# [[hooks]]
# stage = "pre_build"
# command = "sh"
# command_arguments = ["-c", "if [ ! -e tailwind.css ]; then touch tailwind.css; fi"]

[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
port = 1420
open = false
